pipelines:
  default:
    - step:
        name: Mirror to GitHub
        clone:
          depth: full
        script:
          - git remote add github https://juliasveen:${GITHUB_TOKEN}@github.com/juliasveen/LIS5377.git
          - git fetch --unshallow || true
          - git push --force github HEAD:master