-- MySQL Script generated by MySQL Workbench
-- Wed Feb 19 17:09:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jds21k
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `jds21k` ;

-- -----------------------------------------------------
-- Schema jds21k
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jds21k` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
SHOW WARNINGS;
USE `jds21k` ;

-- -----------------------------------------------------
-- Table `jds21k`.`petstore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jds21k`.`petstore` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jds21k`.`petstore` (
  `pst_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_name` VARCHAR(30) NOT NULL,
  `pst_street` VARCHAR(30) NOT NULL,
  `pst_city` VARCHAR(30) NOT NULL,
  `pst_state` CHAR(2) NOT NULL,
  `pst_zip` CHAR(9) NOT NULL,
  `pst_phone` BIGINT UNSIGNED NOT NULL,
  `pst_email` VARCHAR(100) NOT NULL,
  `pst_url` VARCHAR(100) NOT NULL,
  `pst_ytd_sales` DECIMAL(10,2) NOT NULL,
  `pst_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pst_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jds21k`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jds21k`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jds21k`.`customer` (
  `cus_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cus_fname` VARCHAR(15) NOT NULL,
  `cus_lname` VARCHAR(30) NOT NULL,
  `cus_street` VARCHAR(30) NOT NULL,
  `cus_city` VARCHAR(30) NOT NULL,
  `cus_state` CHAR(2) NOT NULL,
  `cus_zip` CHAR(9) NOT NULL,
  `cus_phone` BIGINT NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_balance` DECIMAL(8,2) NOT NULL,
  `cus_total_sales` DECIMAL(8,2) NOT NULL,
  `cus_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`cus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `jds21k`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jds21k`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `jds21k`.`pet` (
  `pet_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pst_id` SMALLINT UNSIGNED NOT NULL,
  `cus_id` SMALLINT UNSIGNED NULL,
  `pet_type` VARCHAR(45) NOT NULL,
  `pet_sex` ENUM('m', 'f') NOT NULL,
  `pet_cost` DECIMAL(6,2) NOT NULL,
  `pet_price` VARCHAR(45) NOT NULL,
  `pet_age` TINYINT NOT NULL,
  `pet_color` VARCHAR(30) NOT NULL,
  `pet_sale_date` DATE NULL,
  `pet_vaccine` ENUM('y', 'n') NOT NULL,
  `pet_neuter` ENUM('y', 'n') NOT NULL,
  `pet_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pet_customer_idx` (`cus_id` ASC) VISIBLE,
  INDEX `fk_pet_petstore1_idx` (`pst_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `jds21k`.`customer` (`cus_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_petstore1`
    FOREIGN KEY (`pst_id`)
    REFERENCES `jds21k`.`petstore` (`pst_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `jds21k`.`petstore`
-- -----------------------------------------------------
START TRANSACTION;
USE `jds21k`;
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Co', '21 Jump St.', 'Tallahassee', 'FL', '32304', 8504096541, 'petco@hotmail.com', 'http://petco.com', 65000, 'notes1');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet Smart', '1 Brentwood Rd.', 'Exeter', 'NH', '03833', 6034522317, 'petsmart@gmail.com', 'http://petsmart.com', 45000, 'notes2');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pet City', '23 Blossom Ct.', 'Seattle', 'WA', '76321', 5412335871, 'petcity@aol.com', 'http://petcity.com', 30000, 'notes3');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pawsome Palace', '1641 Mayhew St.', 'Boston', 'MA', '03885', 6035829541, 'pawsomepalace@hotmail.com', 'http://pawsomepalace.com', 50000, 'notes4');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Fuzzy Friends', '1312 Champions Way', 'Livermore', 'CA', '43265', 7819437651, 'fuzzyfriends@hotmail.com', 'http://fuzzyfriends.com', 40000, 'notes5');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Cuddly Company', '1612 Alameda Dr.', 'Compton', 'CA', '32411', 6035939426, 'cuddlycomp@aol.com', 'http://cuddlycompanions.com', 20000, 'notes6');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Champions of Fluff', '91 Old Orchard Ct.', 'Kittery', 'ME', '32765', 5142398328, 'chapsoffluff@hotmail.com', 'http://championsoffluff.com', 35000, 'notes7');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Pets R Us', '42 Bassett Ln.', 'Newfields', 'OR', '43977', 6598773531, 'petsrus@aol.com', 'http://petsrus.com', 42000, 'notes8');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Doggies Here', '78 High St.', 'Stratham', 'NH', '32077', 6032876519, 'doggieshere@yahoo.com', 'http://doggieshere.com', 50000, 'notes9');
INSERT INTO `jds21k`.`petstore` (`pst_id`, `pst_name`, `pst_street`, `pst_city`, `pst_state`, `pst_zip`, `pst_phone`, `pst_email`, `pst_url`, `pst_ytd_sales`, `pst_notes`) VALUES (DEFAULT, 'Emily\'s Exotics', '981 Pensacola Ave.', 'Tampa', 'FL', '89723', 7812365543, 'emilyexotic@gmail.com', 'http://emilyexotics.com', 25000, 'notes10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `jds21k`.`customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `jds21k`;
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Donald', 'Jaregui', '54 Arcadia Ct.', 'Sarasota', 'FL', '03411', 7832654922, 'donj@yahoo.com', 231.81, 876.32, '');
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Julia', 'Ellis', '1 Brentwood Rd.', 'Portsmouth', 'NH', '03883', 6034921655, 'juliaellis@gmail.com', 342.65, 742.11, '');
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Ulysses', 'Sveen', '12 Yankee Way', 'Boston', 'MA', '06422', 7812396531, 'ulysveen@gmail.com', 123.76, 372.88, NULL);
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Veronica', 'Mars', '32 Kissimee Ct.', 'San Diego', 'CA', '43287', 8096743286, 'vmars@yahoo.com', 244.74, 934.99, NULL);
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Walter', 'White', '1432 Crimson Ave.', 'Bradenton', 'FL', '03421', 8505388219, 'wwhite@aol.com', 355.98, 544.98, NULL);
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Duncan', 'Kane', '1 Indian Rd.', 'East Kingston', 'AZ', '75922', 6512986432, 'duncankane@gmail.com', 422.76, 654.99, NULL);
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Seth', 'Kady', '21 Juniper Lane', 'Dever', 'CO', '54298', 6034982651, 'skady@aol.com', 322.75, 412.87, NULL);
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Molly', 'Thompson', '76 Husky Ave.', 'Portland', 'ME', '04598', 5983285477, 'mothomps@yahoo.com', 599.99, 643.99, NULL);
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Jacob', ' Qualls', '76 Key Pointe Rd.', 'Kittery', 'ME', '03885', 6038074321, 'jacobqualls@gmail.com', 455.85, 943.21, NULL);
INSERT INTO `jds21k`.`customer` (`cus_id`, `cus_fname`, `cus_lname`, `cus_street`, `cus_city`, `cus_state`, `cus_zip`, `cus_phone`, `cus_email`, `cus_balance`, `cus_total_sales`, `cus_notes`) VALUES (DEFAULT, 'Scott', 'Welch', '64 Ramone Ct.', 'New York City', 'NY', '65943', 7812308677, 'scottwelch@aol.com', 338.76, 532.22, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `jds21k`.`pet`
-- -----------------------------------------------------
START TRANSACTION;
USE `jds21k`;
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 2, NULL, 'Chihuahua', 'm', 250, '325', 3, 'cream', '2024-05-27', 'n', 'y', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 3, NULL, 'Labrador', 'f', 350, '425', 2, 'yellow', '2025-01-03', 'y', 'y', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 4, NULL, 'Porteguese Water Dog', 'm', 350, '425', 1, 'black', '2025-02-11', 'y', 'n', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 5, NULL, 'Pitbull', 'f', 200, '275', 2, 'white and light brown', '2024-07-20', 'n', 'n', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 6, NULL, 'Border Collie', 'f', 350, '425', 1, 'white and black', '2024-12-18', 'n', 'y', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 7, NULL, 'Australian Shepard', 'f', 350, '425', 2, 'cream and dark brown', '2025-02-10', 'n', 'y', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 8, NULL, 'German Shepard', 'm', 250, '325', 3, 'brown and black', '2024-10-21', 'n', 'n', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 9, NULL, 'Shitzu', 'f', 300, '375', 4, 'dark brown', '2024-02-16', 'y', 'y', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 10, NULL, 'Doberman', 'm', 300, '375', 3, 'black and light brown', '2024-11-24', 'y', 'n', NULL);
INSERT INTO `jds21k`.`pet` (`pet_id`, `pst_id`, `cus_id`, `pet_type`, `pet_sex`, `pet_cost`, `pet_price`, `pet_age`, `pet_color`, `pet_sale_date`, `pet_vaccine`, `pet_neuter`, `pet_notes`) VALUES (DEFAULT, 1, NULL, 'Golden Retriever', 'f', 350, '425', 2, 'golden brown', '2025-01-16', 'y', 'y', NULL);

COMMIT;

